CHANGELOG.md, doc/arr.md, src/Arr.php, tests/ArrTest.php
=> implement of() method

CHANGELOG.md, doc/arr.md, examples/cheatsheet.php, src/Arr.php, tests/ArrTest.php
=> Add keys() method

CHANGELOG.md, doc/arr.md, examples/cheatsheet.php, src/Arr.php, tests/ArrTest.php
=> implement at() method

CHANGELOG.md, composer.json, doc/arr.md, examples/cheatsheet.php, src/Arr.php, tests/ArrTest.php
=> includes() method

CHANGELOG.md, doc/arr.md, examples/cheatsheet.php, src/Arr.php, tests/ArrTest.php
=> values() method

CHANGELOG.md, doc/table.md, examples/cheatsheet_table.php, src/Classes/Operation.php, src/Table.php, tests/TableTest.php
=> gropuThenApply method

CHANGELOG.md, doc/arr.md, examples/cheatsheet.php, src/Arr.php, tests/Arr/ArrFromTest.php
=> [Arr] add `from`

CHANGELOG.md, doc/arr.md, examples/cheatsheet.php, src/Arr.php, tests/ArrTest.php
=> Implement findIndex

CHANGELOG.md, doc/arr.md, examples/cheatsheet.php, src/Arr.php, tests/ArrTest.php
=> #11 Implement find method

src/Arr.php, src/Classes/Operation.php, src/Table.php, tests/TableTest.php
Improved code style by adding missing return types, removing unused variables, improving phpdocs, removing default values
=> Improved code style

phpstan.neon, src/Table.php
=> phpstan level 5

README.md, src/Arr.php, tests/ArrTest.php
Adds new method `isEmpty()` for checking if array is empty or not
=> Add method isEmpty

CHANGELOG.md, README.md, doc/table.md, examples/cheatsheet_table.php, src/Table.php, tests/TableTest.php
---
name: `orderBy()`
about: Order columns inside of the Table
---
This method allows users to order a column inside of the table in ASC or DESC
=> OrderBy method for the Table Class

CHANGELOG.md, README.md, doc/table.md, src/Table.php, tests/TableTest.php
I've created a merge request to update the `groupBy` method to return a table from the object. This allows us to continue the use of the other methods available within the `Table` object.
I've also created a `transform` method within the `Table` class. This allows us to run a method over a column and change how the value within the table.
=> Update the groupBy method to allow for the return of a Table object

CHANGELOG.md, README.md, examples/cheatsheet_table.php, src/Table.php, tests/TableTest.php
Added method toArray() for Table class.
It closes #53
=> toArray() method, transform Table object into PHP native array

phpstan.neon, src/Arr.php, src/Table.php
This pull request is to increase the level of the PHPStan to 6
It's part of an ongoing issue
https://github.com/Hi-Folks/array/issues/54
=> Increase the PHPStan level to 6

phpstan.neon, src/Arr.php
This pull request is to increase the level of the PHPStan to 7
It's part of an ongoing issue
https://github.com/Hi-Folks/array/issues/54
=> Increase the PHPStan level to 7

src/Classes/Operation.php, tests/TableOperationTest.php
=> adding TableOperationTest for full coverage tests

CHANGELOG.md, composer.json, examples/cheatsheet.php, examples/cheatsheet_table.php, rector.php, src/Arr.php, src/Table.php, src/Traits/Calculable.php, tests/ArrTest.php, tests/TableTest.php
Adding rector with the configuration:
LevelSetList::UP_TO_PHP_80,
SetList::DEAD_CODE
=> Adding Rector

.github/workflows/run-tests.yml, CHANGELOG.md, examples/cheatsheet.php, examples/cheatsheet_table.php, rector.php
Improving Rector with:
LevelSetList::UP_TO_PHP_80,
SetList::DEAD_CODE,
SetList::CODE_QUALITY,
SetList::EARLY_RETURN,
SetList::TYPE_DECLARATION,
SetList::PRIVATIZATION
=> improving rector
